### ISSUE TITLE
Extract this other validations into it's own Validation Request Class

### ISSUE THREAD

**Issue by giunashvili** [RedberryInternship/lukabrazi-laravel-8-from-scratch#5]
https://github.com/RedberryInternship/lukabrazi-laravel-8-from-scratch/blob/0ddedff092bdbecb46dcf288aaf9bdc6e06a8386/app/Http/Controllers/AdminPostController.php#L24-L31

**Comment by giunashvili** [comment]
There are still validations that needs to be extracted from the controllers.
Please make sure that you do this for every validations.

`/app/Http/Controllers/AdminPostController.php`:
![image](https://user-images.githubusercontent.com/39676079/145711254-4fad11af-5e20-49a2-b02c-4def964eb59f.png)

**Comment by giunashvili** [comment]
@Lukabrazi111 

Here validation is not extracted

![image](https://user-images.githubusercontent.com/39676079/145764256-9f4bd63b-098f-4384-bc4f-c39a89fe49ff.png)

**Comment by giunashvili** [comment]
@Lukabrazi111 

Also, here you do not have ValidationRequest, it's basic Request class
![image](https://user-images.githubusercontent.com/39676079/145764361-3704ea79-fb61-491d-8fb2-1b6319954f40.png)

**Comment by giunashvili** [comment]
@Lukabrazi111 

Did you test if updated code was working?

**Comment by Lukabrazi111** [comment]
Oops.. i can't login and register for some reason. i will check right now, i always test but i didn't test register and login

**Comment by Lukabrazi111** [comment]
Now i fixed this issue
